
package hello.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServer", targetNamespace = "http://hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hello/", className = "hello.webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hello/", className = "hello.webservice.SayHelloResponse")
    @Action(input = "http://hello/HelloServer/sayHelloRequest", output = "http://hello/HelloServer/sayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://hello/", className = "hello.webservice.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://hello/", className = "hello.webservice.SendMessageResponse")
    @Action(input = "http://hello/HelloServer/sendMessageRequest", output = "http://hello/HelloServer/sendMessageResponse")
    public String sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        Message arg0);

}
